services:
  db:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=vollmed
      - MYSQL_PASSWORD=dev
      - MYSQL_USER=dev
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3307:3306"
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes:
      - ./.m2:/root/.m2
      - ./target:/app/target
      - ./src:/app/src
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8001:80"
    environment:
      - PMA_HOST=db
      - MYSQL_ROOT_PASSWORD=root
    depends_on:
      - db